// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using act.Repositories.Db;

#nullable disable

namespace act.Repositories.Db.Migrations
{
    [DbContext(typeof(ActDbContext))]
    [Migration("20220829023135_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("act.Services.Model.Interaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelationObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelationSubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationSubjectId", "RelationObjectId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("act.Services.Model.Relation", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId", "ObjectId");

                    b.HasIndex("ObjectId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("act.Services.Model.Interaction", b =>
                {
                    b.HasOne("act.Services.Model.Relation", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationSubjectId", "RelationObjectId");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("act.Services.Model.Relation", b =>
                {
                    b.HasOne("act.Services.Model.Interaction", "Object")
                        .WithMany("AsSubjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("act.Services.Model.Interaction", "Subject")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("act.Services.Model.Interaction", b =>
                {
                    b.Navigation("AsSubjects");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
